version: '3'

services:
  customer-service:
    build: ./customer
    volumes:
      - ./customer:/usr/src/app
    ports:
      - 5001:80

  website:
    image: php:7.0-apache
    volumes:
      - ./website:/var/www/html/
    ports:
      - 5000:80
    depends_on: 
      - customer-service